/// Demo Data Provider
/// This file provides comprehensive dummy data for all screens in the app.
/// Used for UI testing without backend.

import 'package:handyman_provider_flutter/models/booking_list_response.dart';
import 'package:handyman_provider_flutter/models/dashboard_response.dart'
    as dashboard;
import 'package:handyman_provider_flutter/models/handyman_dashboard_response.dart'
    as handyman;
import 'package:handyman_provider_flutter/models/notification_list_response.dart';
import 'package:handyman_provider_flutter/models/payment_list_reasponse.dart';
import 'package:handyman_provider_flutter/models/revenue_chart_data.dart';
import 'package:handyman_provider_flutter/models/service_model.dart';
import 'package:handyman_provider_flutter/models/user_data.dart';
import 'package:handyman_provider_flutter/utils/constant.dart';

/// Demo Dashboard Data for Provider
class DemoDashboardData {
  /// Generate demo provider dashboard response
  static dashboard.DashboardResponse get providerDashboard =>
      dashboard.DashboardResponse(
        status: true,
        totalBooking: 156,
        totalService: 12,
        todayCashAmount: 2450.00,
        totalCashInHand: 15680.50,
        totalActiveHandyman: 8,
        totalRevenue: 125000.00,
        isEmailVerified: 1,
        notificationUnreadCount: 5,
        remainingPayout: 8500.00,
        service: demoServices,
        handyman: demoHandymen,
        upcomingBookings: demoBookings,
        commission: dashboard.Commission(
          id: 1,
          name: 'Standard Commission',
          commission: 15,
          type: COMMISSION_TYPE_PERCENT,
          status: 1,
          createdAt: '2023-01-01 00:00:00',
          updatedAt: '2023-06-15 10:30:00',
        ),
        providerWallet: dashboard.ProviderWallet(
          1,
          'Provider Wallet',
          1,
          15680.50,
          1,
          '2023-01-15 10:30:00',
          '2024-01-10 14:20:00',
        ),
        onlineHandyman: ['2', '3', '5'],
      );

  /// Generate demo handyman dashboard response
  static handyman.HandymanDashBoardResponse get handymanDashboard =>
      handyman.HandymanDashBoardResponse(
        status: true,
        totalBooking: 45,
        todayBooking: 3,
        totalRevenue: 25000.00,
        todayCashAmount: 350.00,
        totalCashInHand: 5000.00,
        isHandymanAvailable: 1,
        completedBooking: 42,
        isEmailVerified: 1,
        notificationUnreadCount: 3,
        upcomingBookings: demoBookings.take(3).toList(),
        commission: handyman.Commission(
          id: 1,
          name: 'Handyman Commission',
          commission: 10,
          type: COMMISSION_TYPE_PERCENT,
          status: 1,
        ),
      );

  /// Demo Revenue Chart Data
  static List<RevenueChartData> get revenueChartData => [
        RevenueChartData(month: 'Jan', revenue: 12500),
        RevenueChartData(month: 'Feb', revenue: 15000),
        RevenueChartData(month: 'Mar', revenue: 11800),
        RevenueChartData(month: 'Apr', revenue: 18200),
        RevenueChartData(month: 'May', revenue: 16500),
        RevenueChartData(month: 'Jun', revenue: 21000),
        RevenueChartData(month: 'Jul', revenue: 19500),
        RevenueChartData(month: 'Aug', revenue: 22000),
        RevenueChartData(month: 'Sep', revenue: 17800),
        RevenueChartData(month: 'Oct', revenue: 20500),
        RevenueChartData(month: 'Nov', revenue: 23000),
        RevenueChartData(month: 'Dec', revenue: 25000),
      ];
}

/// Demo Services List
List<ServiceData> get demoServices => [
      ServiceData(
        id: 1,
        name: 'Home Cleaning',
        categoryId: 1,
        categoryName: 'Cleaning',
        providerId: 1,
        providerName: 'John Provider',
        price: 75.00,
        type: SERVICE_TYPE_FIXED,
        discount: 10,
        duration: '02:00',
        status: 1,
        description:
            'Professional home cleaning service including dusting, mopping, and sanitization.',
        isFeatured: 1,
        totalReview: 45,
        totalRating: 4.8,
        visitType: VISIT_OPTION_ON_SITE,
        imageAttachments: [
          'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400',
        ],
      ),
      ServiceData(
        id: 2,
        name: 'Electrical Repair',
        categoryId: 2,
        categoryName: 'Electrical',
        providerId: 1,
        providerName: 'John Provider',
        price: 50.00,
        type: SERVICE_TYPE_HOURLY,
        discount: 0,
        duration: '01:00',
        status: 1,
        description:
            'Expert electrical repair services for all household needs.',
        isFeatured: 1,
        totalReview: 32,
        totalRating: 4.6,
        visitType: VISIT_OPTION_ON_SITE,
        imageAttachments: [
          'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400',
        ],
      ),
      ServiceData(
        id: 3,
        name: 'Plumbing Service',
        categoryId: 3,
        categoryName: 'Plumbing',
        providerId: 1,
        providerName: 'John Provider',
        price: 60.00,
        type: SERVICE_TYPE_HOURLY,
        discount: 5,
        duration: '01:30',
        status: 1,
        description:
            'Professional plumbing services including leak repair, pipe fitting, and drainage.',
        isFeatured: 0,
        totalReview: 28,
        totalRating: 4.5,
        visitType: VISIT_OPTION_ON_SITE,
        imageAttachments: [
          'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400',
        ],
      ),
      ServiceData(
        id: 4,
        name: 'AC Repair & Service',
        categoryId: 4,
        categoryName: 'Appliance',
        providerId: 1,
        providerName: 'John Provider',
        price: 85.00,
        type: SERVICE_TYPE_FIXED,
        discount: 15,
        duration: '02:30',
        status: 1,
        description:
            'Complete AC repair and maintenance service including gas refill and cleaning.',
        isFeatured: 1,
        totalReview: 56,
        totalRating: 4.9,
        visitType: VISIT_OPTION_ON_SITE,
        imageAttachments: [
          'https://images.unsplash.com/photo-1631545806609-10d45f7a8532?w=400',
        ],
      ),
      ServiceData(
        id: 5,
        name: 'Painting Service',
        categoryId: 5,
        categoryName: 'Painting',
        providerId: 1,
        providerName: 'John Provider',
        price: 40.00,
        type: SERVICE_TYPE_HOURLY,
        discount: 0,
        duration: '04:00',
        status: 1,
        description:
            'Interior and exterior painting services with premium quality paints.',
        isFeatured: 0,
        totalReview: 19,
        totalRating: 4.4,
        visitType: VISIT_OPTION_ON_SITE,
        imageAttachments: [
          'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=400',
        ],
      ),
      ServiceData(
        id: 6,
        name: 'Online Consultation',
        categoryId: 6,
        categoryName: 'Consulting',
        providerId: 1,
        providerName: 'John Provider',
        price: 25.00,
        type: SERVICE_TYPE_FIXED,
        discount: 0,
        duration: '00:30',
        status: 1,
        description:
            'Get expert advice online for your home improvement projects.',
        isFeatured: 0,
        totalReview: 12,
        totalRating: 4.7,
        visitType: VISIT_OPTION_ONLINE,
        imageAttachments: [
          'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
        ],
      ),
    ];

/// Demo Handymen List
List<UserData> get demoHandymen => [
      UserData(
        id: 2,
        firstName: 'Mike',
        lastName: 'Johnson',
        email: 'mike@handyman.com',
        userType: USER_TYPE_HANDYMAN,
        contactNumber: '+1234567891',
        status: 1,
        displayName: 'Mike Johnson',
        profileImage: 'https://i.pravatar.cc/300?u=mike',
        designation: 'Senior Handyman',
        handymanRating: 4.8,
        isHandymanAvailable: true,
        isVerifiedHandyman: 1,
      ),
      UserData(
        id: 3,
        firstName: 'David',
        lastName: 'Williams',
        email: 'david@handyman.com',
        userType: USER_TYPE_HANDYMAN,
        contactNumber: '+1234567892',
        status: 1,
        displayName: 'David Williams',
        profileImage: 'https://i.pravatar.cc/300?u=david',
        designation: 'Electrician',
        handymanRating: 4.6,
        isHandymanAvailable: true,
        isVerifiedHandyman: 1,
      ),
      UserData(
        id: 4,
        firstName: 'Robert',
        lastName: 'Brown',
        email: 'robert@handyman.com',
        userType: USER_TYPE_HANDYMAN,
        contactNumber: '+1234567893',
        status: 1,
        displayName: 'Robert Brown',
        profileImage: 'https://i.pravatar.cc/300?u=robert',
        designation: 'Plumber',
        handymanRating: 4.5,
        isHandymanAvailable: false,
        isVerifiedHandyman: 1,
      ),
      UserData(
        id: 5,
        firstName: 'James',
        lastName: 'Davis',
        email: 'james@handyman.com',
        userType: USER_TYPE_HANDYMAN,
        contactNumber: '+1234567894',
        status: 1,
        displayName: 'James Davis',
        profileImage: 'https://i.pravatar.cc/300?u=james',
        designation: 'Painter',
        handymanRating: 4.7,
        isHandymanAvailable: true,
        isVerifiedHandyman: 0,
      ),
    ];

/// Demo Bookings List
List<BookingData> get demoBookings => [
      BookingData(
        id: 1001,
        serviceName: 'Home Cleaning',
        serviceId: 1,
        customerName: 'Alice Smith',
        customerId: 101,
        customerImage: 'https://i.pravatar.cc/300?u=alice',
        providerId: 1,
        providerName: 'John Provider',
        providerImage: 'https://i.pravatar.cc/300?u=provider',
        status: BOOKING_STATUS_PENDING,
        statusLabel: 'Pending',
        date: '2024-01-20 10:00:00',
        address: '123 Main Street, New York, NY 10001',
        visitType: VISIT_OPTION_ON_SITE,
        amount: 75.00,
        totalAmount: 82.50,
        discount: 10,
        type: SERVICE_TYPE_FIXED,
        paymentStatus: PENDING,
        paymentMethod: PAYMENT_METHOD_COD,
        quantity: 1,
        description: 'Deep cleaning of 3-bedroom apartment',
        imageAttachments: [
          'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400',
        ],
      ),
      BookingData(
        id: 1002,
        serviceName: 'Electrical Repair',
        serviceId: 2,
        customerName: 'Bob Johnson',
        customerId: 102,
        customerImage: 'https://i.pravatar.cc/300?u=bob',
        providerId: 1,
        providerName: 'John Provider',
        status: BOOKING_STATUS_ACCEPT,
        statusLabel: 'Accepted',
        date: '2024-01-21 14:30:00',
        address: '456 Oak Avenue, Brooklyn, NY 11201',
        visitType: VISIT_OPTION_ON_SITE,
        amount: 100.00,
        totalAmount: 100.00,
        discount: 0,
        type: SERVICE_TYPE_HOURLY,
        paymentStatus: PENDING,
        paymentMethod: PAYMENT_METHOD_STRIPE,
        quantity: 2,
        description: 'Fix electrical outlets in living room',
        handyman: [
          Handyman(
            id: 1,
            bookingId: 1002,
            handymanId: 2,
            handyman: demoHandymen[0],
          ),
        ],
      ),
      BookingData(
        id: 1003,
        serviceName: 'Plumbing Service',
        serviceId: 3,
        customerName: 'Carol White',
        customerId: 103,
        customerImage: 'https://i.pravatar.cc/300?u=carol',
        providerId: 1,
        providerName: 'John Provider',
        status: BOOKING_STATUS_ON_GOING,
        statusLabel: 'On Going',
        date: '2024-01-19 09:00:00',
        address: '789 Pine Street, Queens, NY 11375',
        visitType: VISIT_OPTION_ON_SITE,
        amount: 90.00,
        totalAmount: 85.50,
        discount: 5,
        type: SERVICE_TYPE_HOURLY,
        paymentStatus: PENDING,
        paymentMethod: PAYMENT_METHOD_COD,
        quantity: 1,
        description: 'Fix kitchen sink leak',
        startAt: '2024-01-19 09:15:00',
        handyman: [
          Handyman(
            id: 2,
            bookingId: 1003,
            handymanId: 4,
            handyman: demoHandymen[2],
          ),
        ],
      ),
      BookingData(
        id: 1004,
        serviceName: 'AC Repair & Service',
        serviceId: 4,
        customerName: 'Daniel Green',
        customerId: 104,
        customerImage: 'https://i.pravatar.cc/300?u=daniel',
        providerId: 1,
        providerName: 'John Provider',
        status: BOOKING_STATUS_COMPLETED,
        statusLabel: 'Completed',
        date: '2024-01-15 11:00:00',
        address: '321 Elm Road, Manhattan, NY 10016',
        visitType: VISIT_OPTION_ON_SITE,
        amount: 85.00,
        totalAmount: 72.25,
        discount: 15,
        type: SERVICE_TYPE_FIXED,
        paymentStatus: PAID,
        paymentMethod: PAYMENT_METHOD_STRIPE,
        quantity: 1,
        description: 'Annual AC maintenance and gas refill',
        startAt: '2024-01-15 11:15:00',
        endAt: '2024-01-15 13:30:00',
        totalRating: 5,
        totalReview: 1,
      ),
      BookingData(
        id: 1005,
        serviceName: 'Painting Service',
        serviceId: 5,
        customerName: 'Eva Martinez',
        customerId: 105,
        customerImage: 'https://i.pravatar.cc/300?u=eva',
        providerId: 1,
        providerName: 'John Provider',
        status: BOOKING_STATUS_CANCELLED,
        statusLabel: 'Cancelled',
        date: '2024-01-18 08:00:00',
        address: '654 Maple Drive, Bronx, NY 10451',
        visitType: VISIT_OPTION_ON_SITE,
        amount: 160.00,
        totalAmount: 160.00,
        discount: 0,
        type: SERVICE_TYPE_HOURLY,
        paymentStatus: PENDING,
        paymentMethod: PAYMENT_METHOD_COD,
        quantity: 4,
        description: 'Paint living room and bedroom',
        reason: 'Customer requested cancellation due to schedule conflict',
        isCancelled: 1,
      ),
    ];

/// Demo Notifications List
List<NotificationData> get demoNotifications => [
      NotificationData(
        id: '1',
        readAt: null,
        createdAt:
            DateTime.now().subtract(const Duration(minutes: 5)).toString(),
        data: Data(
          id: 1001,
          type: ADD_BOOKING,
          subject: 'New Booking',
          message: 'You have a new booking for Home Cleaning',
          notificationType: NOTIFICATION_TYPE_BOOKING,
        ),
      ),
      NotificationData(
        id: '2',
        readAt: null,
        createdAt: DateTime.now().subtract(const Duration(hours: 1)).toString(),
        data: Data(
          id: 1002,
          type: ASSIGNED_BOOKING,
          subject: 'Booking Assigned',
          message:
              'Mike Johnson has been assigned to Electrical Repair booking',
          notificationType: NOTIFICATION_TYPE_BOOKING,
        ),
      ),
      NotificationData(
        id: '3',
        readAt: DateTime.now().subtract(const Duration(hours: 2)).toString(),
        createdAt: DateTime.now().subtract(const Duration(hours: 3)).toString(),
        data: Data(
          id: 1003,
          type: UPDATE_BOOKING_STATUS,
          subject: 'Booking Status Updated',
          message: 'Plumbing Service booking is now in progress',
          notificationType: NOTIFICATION_TYPE_BOOKING,
        ),
      ),
      NotificationData(
        id: '4',
        readAt: DateTime.now().subtract(const Duration(days: 1)).toString(),
        createdAt: DateTime.now().subtract(const Duration(days: 1)).toString(),
        data: Data(
          id: 1004,
          type: PAID_FOR_BOOKING,
          subject: 'Payment Received',
          message: 'Payment of \$72.25 received for AC Repair & Service',
          notificationType: NOTIFICATION_TYPE_BOOKING,
        ),
      ),
      NotificationData(
        id: '5',
        readAt: DateTime.now().subtract(const Duration(days: 2)).toString(),
        createdAt: DateTime.now().subtract(const Duration(days: 2)).toString(),
        data: Data(
          id: 1005,
          type: CANCEL_BOOKING,
          subject: 'Booking Cancelled',
          message: 'Painting Service booking has been cancelled by customer',
          notificationType: NOTIFICATION_TYPE_BOOKING,
        ),
      ),
    ];

/// Demo Payments List
List<PaymentData> get demoPayments => [
      PaymentData(
        id: 2001,
        bookingId: 1004,
        customerId: 104,
        customerName: 'Daniel Green',
        paymentMethod: PAYMENT_METHOD_STRIPE,
        paymentStatus: PAID,
        txnId: 'TXN_20240115_001',
        totalAmount: 72.25,
        date: '2024-01-15 13:45:00',
      ),
      PaymentData(
        id: 2002,
        bookingId: 1001,
        customerId: 101,
        customerName: 'Alice Smith',
        paymentMethod: PAYMENT_METHOD_COD,
        paymentStatus: PENDING,
        totalAmount: 82.50,
        date: '2024-01-20 10:00:00',
      ),
      PaymentData(
        id: 2003,
        bookingId: 1002,
        customerId: 102,
        customerName: 'Bob Johnson',
        paymentMethod: PAYMENT_METHOD_STRIPE,
        paymentStatus: PENDING,
        totalAmount: 100.00,
        date: '2024-01-21 14:30:00',
      ),
    ];

/// Demo Customers List
List<UserData> get demoCustomers => [
      UserData(
        id: 101,
        firstName: 'Alice',
        lastName: 'Smith',
        email: 'alice@customer.com',
        userType: IS_USER,
        contactNumber: '+1555000101',
        status: 1,
        displayName: 'Alice Smith',
        profileImage: 'https://i.pravatar.cc/300?u=alice',
        address: '123 Main Street, New York, NY 10001',
        totalBooking: 5,
      ),
      UserData(
        id: 102,
        firstName: 'Bob',
        lastName: 'Johnson',
        email: 'bob@customer.com',
        userType: IS_USER,
        contactNumber: '+1555000102',
        status: 1,
        displayName: 'Bob Johnson',
        profileImage: 'https://i.pravatar.cc/300?u=bob',
        address: '456 Oak Avenue, Brooklyn, NY 11201',
        totalBooking: 3,
      ),
      UserData(
        id: 103,
        firstName: 'Carol',
        lastName: 'White',
        email: 'carol@customer.com',
        userType: IS_USER,
        contactNumber: '+1555000103',
        status: 1,
        displayName: 'Carol White',
        profileImage: 'https://i.pravatar.cc/300?u=carol',
        address: '789 Pine Street, Queens, NY 11375',
        totalBooking: 8,
      ),
      UserData(
        id: 104,
        firstName: 'Daniel',
        lastName: 'Green',
        email: 'daniel@customer.com',
        userType: IS_USER,
        contactNumber: '+1555000104',
        status: 1,
        displayName: 'Daniel Green',
        profileImage: 'https://i.pravatar.cc/300?u=daniel',
        address: '321 Elm Road, Manhattan, NY 10016',
        totalBooking: 12,
      ),
      UserData(
        id: 105,
        firstName: 'Eva',
        lastName: 'Martinez',
        email: 'eva@customer.com',
        userType: IS_USER,
        contactNumber: '+1555000105',
        status: 1,
        displayName: 'Eva Martinez',
        profileImage: 'https://i.pravatar.cc/300?u=eva',
        address: '654 Maple Drive, Bronx, NY 10451',
        totalBooking: 2,
      ),
    ];
